/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-04 14:58:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class User_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("   \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>hritik Gupta</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write(".main{\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    background:#FAF0E6;\n");
      out.write("    font-family: Sul Sans,Helvetica Neue,Helvetica,Roboto,Arial,sans-serif;\n");
      out.write("    font-weight: 400;\n");
      out.write("    line-height: 1.5;\n");
      out.write("    color: #FFFAFA;\n");
      out.write("    -webkit-font-smoothing: antialiased\n");
      out.write("	background-color: #FFFAFA;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bx {\n");
      out.write("	padding: 0;\n");
      out.write("  	background-color: black;\n");
      out.write("  	overflow: hidden;\n");
      out.write("  	border-radius: 0;\n");
      out.write("  	height:150px;\n");
      out.write("  	max-height: 210px;\n");
      out.write(" 	margin: auto;\n");
      out.write("  	padding-top: 20px;\n");
      out.write("  	border-bottom-left-radius: 20px;\n");
      out.write("  	border-bottom-right-radius: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".head{\n");
      out.write("	font-family: Garamond;\n");
      out.write("	font-size:30px;\n");
      out.write("	color: green;\n");
      out.write("	padding:1px;\n");
      out.write("	max-width:500px;\n");
      out.write("	padding-top: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sh {\n");
      out.write("  position: absolute;\n");
      out.write("  top: 21%;\n");
      out.write("  left: 9%;\n");
      out.write("  transform: translate(-50%, -50%);\n");
      out.write("  font-family: Garamond;\n");
      out.write("  color: green;\n");
      out.write("  font-size:27px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".active{\n");
      out.write("	display :block;\n");
      out.write("	text-decoration: none;\n");
      out.write("	float: right;\n");
      out.write("	padding: 1%;\n");
      out.write("	margin: auto;\n");
      out.write("	margin-right : 1%;\n");
      out.write("	margin-left : 1%;\n");
      out.write("	font-size: 27px;\n");
      out.write("	font-family: Garamond;\n");
      out.write("	color: green;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".active a:hover {\n");
      out.write("	background: gray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".img{\n");
      out.write("	position: absolute;\n");
      out.write("	margin-left: 2%;	\n");
      out.write("	margin-right: 2%;\n");
      out.write("	max-height: 200px;\n");
      out.write("	max-width: 400px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".info{\n");
      out.write("	color: black;\n");
      out.write("	font-family: Garamond;\n");
      out.write("	float: right;\n");
      out.write("	padding-right: 15px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"main\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"bx\">\n");
      out.write("<div class=\"container\">\n");
      out.write("<img class=\"img\" alt=\"Snow\" src=\"sporty.png\">\n");
      out.write("<h3 class=\"sh\"></h3>\n");
      out.write("</div>\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<a class=\"active\" href=\"HOME_SCREEN.jsp\"><b>LOG-OUT</b></a>\n");
      out.write("<a class=\"active\" href=\"user_login.jsp\"><b>LOGIN</b></a>\n");
      out.write("<a class=\"active\" href=\"insert_user.jsp\"><b>REGISTER</b></a>\n");
      out.write("<a class=\"active\" href=\"User_main.jsp\"><b>HOME</b></a>\n");
      out.write("</div>\n");
      out.write("<h4 class=\"info\">User Page</h4>\n");
      out.write("<br>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
